# Generated by Django 4.2.4 on 2023-09-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_id', models.PositiveIntegerField()),
                ('filename', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
    ]
