# Generated by Django 4.2.4 on 2023-09-14 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0002_pipelineartifact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PipelineArtifact',
        ),
    ]
